# NumPy Exercises - Assignment 1 - 21BCE0369 - Anurag Jawalkar

In [2]:
import numpy as np

In [7]:
a0 = np.zeros(10)
print(a0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
a1 = np.ones(10)
print(a1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
a5= np.ones(10)*5
print(a5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
array = np.arange(10, 51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
even_array = np.arange(10, 51, 2)
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
rand_number = np.random.rand()
print(rand_number)

0.9470179455983957


In [16]:
rand_numbers = np.random.randn(25)
print(rand_numbers)

[-0.01749663  1.41610958 -0.32429457 -2.63145886  0.82015491 -0.16519046
 -0.87356191 -0.45326202  1.33252885  0.26420913  0.50338762 -0.46463448
 -0.49067612  1.06968102 -0.66753774  1.28464888 -0.34723421 -0.5115096
  0.85035864 -0.34706235 -0.44707465  1.70156151  1.92659072  0.51477459
  0.99400034]


In [18]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [19]:
points = np.linspace(0, 1, 20)
print(points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [20]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
m2 = np.arange(12, 26).reshape(3, 4)
m2

ValueError: cannot reshape array of size 14 into shape (3,4)

In [33]:
print(20)

20


In [35]:
m3 = np.array([[2], [7], [12]])
m3

array([[ 2],
       [ 7],
       [12]])

In [36]:
array = np.array([21, 22, 23, 24, 25])
array

array([21, 22, 23, 24, 25])

In [37]:
m4 = np.array([[16, 17, 18, 19, 20],
                          [21, 22, 23, 24, 25]])
m4

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
sum = np.sum(mat)
print(sum)

325


In [39]:
std_dev = np.std(mat)
print(std_dev)

7.211102550927978


In [40]:
column_sum = np.sum(mat, axis=0)
print(column_sum)

[55 60 65 70 75]


# Thank You!